### ISSUE TITLE
Multi-field validation

### ISSUE THREAD

**Issue by theleoborges** [leonardoborges/bouncer#21]
Currently if I want to validate that `:from` is less than `:to` in a map I have to write a custom validator on the following lines:

``` clojure
(def subject {:from 20 :to 10})

(defn less-than [max]
  (fn [value]
    (< value max)))

(b/validate subject
            :from [[v/required (less-than (:to subject))]]
            :to   [[v/required]])
```

I hadn't implemented this feature so far as I didn't come up with an API I was happy with. After some thought I have some ideas that would allow the previous example to be written as:

``` clojure
(b/validate subject
            :from [[v/required]]
            :to   [[v/required]]
            [:from :to] [[< :message "From should be less than to"]])
```

This would be flexible enough to allow for other usages. For example, password confirmation could be validated as such:

``` clojure
(b/validate subject
            :password     [[v/required]]
            :confirmation [[v/required :pre (comp not nil? :password)]]
            [:password :confirmation] [[= :message "Passwords should match."]])
```

Validator functions used in multi-field validations need an arity equal to the length of keywords in the vector preceding the validators.

How does this API look to you?

**Comment by limist** [comment]
Bumped into this issue recently; used the workaround solution above (thanks @amogh-talpallikar ), which works. If there are no plans to rollout the new API, some documentation about mult-field validation would be really helpful

**Comment by OliverM** [comment]
I've bumped into this too. The workaround above won't work if you've been defining common sets of validators to include in larger validation suites, as they're defined using (def {field name validation-set}), with no access to the map being validated. I've not tried the multi-field validation branch as I'm not sure what stage it's at vs. the main branch.
