### ISSUE TITLE
v/datetime does not work in clojurescript

### ISSUE THREAD

**Issue by sonwh98** [leonardoborges/bouncer#32]
v/datetime uses jodatime so it makes sense that it doesn't work with clojurescript.  are there plans to make this validator work in clojurescript?

**Comment by leonardoborges** [comment]
Hi @sonwh98 ,

The datetime validator should work in clojurescript as well. It uses a different library when it's in javascript.

If that is not the case, can you please let us know what version of bouncer you're using?

**Comment by sonwh98** [comment]
thanks. I missed the note about ;; cljs-time for clojurescript users

**Comment by leonardoborges** [comment]
Cool! I'm glad you sorted it out :)
