### ISSUE TITLE
Version ranges found for:

### ISSUE THREAD

**Issue by vsnguyen** [leonardoborges/bouncer#34]
lein deps
WARNING!!! version ranges found for:
[bouncer "0.3.2-SNAPSHOT"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [org.clojure/clojure "[1.3.0,)"]
Consider using [bouncer "0.3.2-20141118.091354-2" :exclusions [org.clojure/clojure]].
[bouncer "0.3.2-SNAPSHOT"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [net.cgrand/regex "1.1.0"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [bouncer "0.3.2-20141118.091354-2" :exclusions [org.clojure/clojure]].
[bouncer "0.3.2-SNAPSHOT"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [net.cgrand/parsley "0.9.1"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [bouncer "0.3.2-20141118.091354-2" :exclusions [org.clojure/clojure]].
[bouncer "0.3.2-SNAPSHOT"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [net.cgrand/parsley "0.9.1"] -> [net.cgrand/regex "1.1.0"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [bouncer "0.3.2-20141118.091354-2" :exclusions [org.clojure/clojure]].

**Comment by leonardoborges** [comment]
Fixed by 04565410542a0b94e92fd5be3dafdd0cff32e786
