### ISSUE TITLE
provide optional validators

### ISSUE THREAD

**Issue by vvvvalvalval** [leonardoborges/bouncer#36]
I often find myself wanting to validate attributes of maps only if they are present, for example when validating the body of a `PATCH` HTTP request.

I thought I could achieve that by omitting `required` in validation maps, but then realized that this would not work for anything but `number, `matches` and `positive`.

Which leads me to 2 potential issues:
1. The behaviour of `:optional` and `required` may be a bit confusing at the moment. The fact that `required` exists in the API would let you think that the other validators are optional by default, as meant to be composed with `required`; this is made worse by the fact that for example `number` is optional but `integer` is not (is there a reason for this I don't see?). I would suggest to question the current design to make all provided validators `:optional` (which would be a breaking change of course, but could be considered for 1.0) or to document explicitly in the README which of the default validators are `:optional`.
2. Back to my initial problem: I believe optional validators are needed. I ended up doing something like this in my app code:

```clojure
  (ns my.own.validators
    (:require [bouncer.validators :as v]))
  
  (def string?? (vary-meta v/string assoc
                           :optional true
                           :validator ::string??))
  (def boolean?? (vary-meta v/string assoc
                           :optional true
                           :validator ::boolean??))
  ;; etc.
```

What do you think?

**Comment by vvvvalvalval** [comment]
Btw, I'm totally willing to submit PRs for both issues I raised, just waiting for your initial validation (pun intended).

**Comment by leonardoborges** [comment]
You're right in that there is currently some inconsistencies in the use of `:optional`. At this point it's mostly historical reasons but I had planned to unify that at some stage so thanks for bringing that up.

To that end, I think we need to make all built-in validators optional and update the docs. This would require a new major version as it's likely to break people's code.

I'm happy to review a PR for that but I'd probably hold off on a release so we can bundle a few more things in the same major version. Having said that, I can push a snapshot version with the change for people to experiment.

**Comment by vvvvalvalval** [comment]
I agree with making everything optional by default. I'll see if I can make a PR when I get some free time but I'm a bit overwhelmed right now :/. I'm not using bouncer in any active project right now, so I don't want to press the matter :)

**Comment by jonase** [comment]
When I started looking at bouncer I assumed (due to the existence of `v/required`) that every validator was "optional": 

* `:foo [v/string] ;; :foo is optional and its value (if it exists) must be a string`
* `:foo [v/required v/string] ;; :foo is required and its value must be a string` 

so I was a bit surprised that many of the validators "implied" `v/required`.
