### ISSUE TITLE
namespace-qualify meta keys

### ISSUE THREAD

**Issue by vvvvalvalval** [leonardoborges/bouncer#37]
For the next major release, I suggest to change the `:validator`, `:default-message-format` and `:optional` meta keys to their namespace-qualified counterparts `:bouncer.validators/validator`, `:bouncer.validators/default-message-format` and `:bouncer.validators/optional`.

Given that any library can add stuff to metas, this seems safer.

**Comment by leonardoborges** [comment]
Sorry it took me so long to reply.

This seems like a reasonable things to do. If you're willing to submit a PR, I'm happy to review it.

Ideally the way `defvalidator` is used shouldn't change so users can still simply specify `:optional` and the macro will appropriately namespace it for you. Thoughts?

**Comment by vvvvalvalval** [comment]
Seems OK for compatibility, but I would still remove it on the next major release, better to keep things as simple and not confusing as possible IMHO :).

**Comment by leonardoborges** [comment]
Not opposed to this change at all but don't have the time to make the change at the moment. A PR is welcome. Closing this for now.
