### ISSUE TITLE
feature: remove pairs that validation do not handle

### ISSUE THREAD

**Issue by defclass** [leonardoborges/bouncer#39]
Hi @Atlassian, I think it would be great to add feature that  remove pairs that validation do not handle. eg:

```
(def person {:name "Leo" :age 15})

(b/validate person
    :name v/required
    :age  v/required)
```

this can pass, but

```
(def person {:name "Leo" :age 15 :user_id 1})

(b/validate person
    :name v/required
    :age  v/required)
```
will return error, or just return

```
 [nil  {:name "Leo", :bouncer.core/errors {:age ("age must be present")}}
 ;; add a map that only validation pass,eg:
 ;; {:name "Leo" :age 15 }]

```
As usual scene after validation , we just merge the map to some origin map from database. Right now ,we have to check every pair in map to ensure no extra unsafe pairs. 

Please consider this feature,  thanks !

**Comment by leonardoborges** [comment]
I personally don't think bouncer should make any efforts of removing key value pairs by default. This *could* be added as an option but I haven't had a use case for it yet. Yours is an interesting one. 

I'll ping some people who have contributed recently so see if they have any thoughts: @mishadoff @Skinney

**Comment by Skinney** [comment]
I agree with @leonardoborges that bouncer shouldn't remove key value pairs by default. But I definitely think this is a use case that we should provide some sort of situation for. I have three suggestions:

1. Create a new function, called `conform` or something similar, that removes all pairs not handled by a call to validate. This can be easily nested like this:

```clj
(-> some-map
      bouncer/conform
      (bouncer/validate map-schema))
```

2. Reject unhandled pairs by default. This is how prismatic/schema does it.

```clj
(bouncer/validate {:name "Robin", :age 26} {:name [v/required v/string]})
=> [{:name "Robin", :age 26}, {:bouncer.core/errors {:age '("age is not allowed")}}]
```

3. Create a new validate function, `strict-validate`, that performs option 2.

I think either 2 or 3 would be best.

**Comment by leonardoborges** [comment]
I'm leaning towards option 3. Though I'll let it stew for a bit.

**Comment by mishadoff** [comment]
I also think it should not be default behaviour. Because most of the time validation should check only specific keys and ignore the others. Assume we need to serve a couple of messages 

```
{:type :message :text "Hello"}
{:type :event :key :clear-cache :requested-by "admin"}
```

And our validator need to check the type is registered in the system (e.g in keyset #{:event :message})

If you really need truncate your map to specific keys, use standard clojure function `select-keys`
https://clojuredocs.org/clojure.core/select-keys

**Comment by defclass** [comment]
@mishadoff  that's right  , thanks for all your help.
