### ISSUE TITLE
v/matches implies v/required?

### ISSUE THREAD

**Issue by jonase** [leonardoborges/bouncer#40]
I'm not sure if this is intended behaviour but

```clojure
(bouncer/validate {}
                  :id [v/string [v/matches #"a*"]])
```
evaluates to 
```clojure
[{:id ("id must be a string")} {:bouncer.core/errors {:id ("id must be a string")}}]
```
I would have expected the validation to pass since `:id` is not `v/required`.

If this is expected how do I create a validator where an **optional** string value must match a regex only if the key exists?

**Edit** After some digging it's actually `v/string` that makes the key-value non-optional. This was a surprise for me

**Comment by leonardoborges** [comment]
This has been changed on #41 so bouncer will behave like this:

```clojure
user=> (b/validate {} :id [v/string [v/matches #"a*"]])
[nil {}]
user=> (b/validate {} :id [v/required v/string [v/matches #"a*"]])
[{:id ("id must be present")} {:bouncer.core/errors {:id ("id must be present")}}]
```

I've just released a [new version](https://clojars.org/bouncer/versions/1.0.0) containing this change. Give that a go and let me know if you run into issues.
