### ISSUE TITLE
Errors in a list, and short circuiting

### ISSUE THREAD

**Issue by Skinney** [leonardoborges/bouncer#42]
The readme makes a point of short circuiting. If a key has more than one validator, only the error message from the first failing validator is returned. Considering this, why are error-strings returned as lists?

Example:
```
(s/validate {:age "NaN"}
                 :age [v/required v/number v/positive])
=> {:age (":age is not a number")} ;; why is error message in a list?
```

**Comment by leonardoborges** [comment]
Legacy. Originally bouncer would not short circuit validations and therefore would return all messages in a list. 

I'm not opposed to changing it but haven't had a compelling reason to do so yet.

**Comment by Skinney** [comment]
It's not a big deal, just wondering :)

**Comment by leonardoborges** [comment]
A lot of the time these things come down to legacy :) I'll close the issue for now and revisit in the future, possibly next major version since this wouldn't be backwards compatible.
