### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by codepodu** [leonardoborges/bouncer#44]
Hi,

I like the change with all validators being optional by default. Could you please release a new version so that we can use it?

Thanks!

**Comment by smaant** [comment]
+1

**Comment by Skinney** [comment]
@leonardoborges ?

**Comment by leonardoborges** [comment]
Sorry for the delay guys. I plan on releasing a new version this week, before going on holidays.

**Comment by Skinney** [comment]
sweeeeet

**Comment by leonardoborges** [comment]
[1.0.0 pushed to Clojars](https://clojars.org/bouncer/versions/1.0.0)
