### ISSUE TITLE
Should have a way to validate that no extra keys are given in map

### ISSUE THREAD

**Issue by b-ryan** [leonardoborges/bouncer#47]
Example code:

```clj
(b/valid? {:a "foo" :b "bar"} :a v/string)
=> true
```

I would have expected this to be invalid due to `:b` existing in the map, but there being no validator for it.

**Comment by leonardoborges** [comment]
This issues has been discussed in #39 

The OP ended up closing the issue but have a look at it. There's some info on the rationale as well as suggested ways of implementing it should we decide to do it. Feel free to re-open that issue.
