### ISSUE TITLE
Validators aren't applied if defined after applying a common set

### ISSUE THREAD

**Issue by OliverM** [leonardoborges/bouncer#49]
According to the docs, you [can define maps of validations](https://github.com/leonardoborges/bouncer#validator-sets) that can be composed with other validations to factor out common sets. I can't get this to work. At the repl, if I do:
```clj
(require '[bouncer.core :as b])
(require '[bouncer.validators :as bv])

(def common-validations 
  {:field1 [[bv/required :message "Nothing given for field one."]]})

(b/validate {:field1 "Present" :field2 2}
            common-validations
            :field2 [[bv/boolean :message "Field 2 not a boolean"]])

(b/validate {:field1 "Present" :field2 2}  
            common-validations
            :field2 [[bv/boolean :message "Field 2 not a boolean"]]) ;; shouldn't validate :field2
```
Instead of a validation error, the last invocation above returns ```[nil {:field1 "Present", :field2 2}]``` - e.g. the second field 2 boolean test isn't applied. If I drop the common-validations part, it runs as expected:

```clj
(b/validate {:field1 "Present" :field2 2}
            :field2 [[bv/boolean :message "Field 2 not a boolean"]])
```
returns 
```clj
[{:field2 ("Field 2 not a boolean")}
 {:field1 "Present", :field2 2, :bouncer.core/errors {:field2 ("Field 2 not a boolean")}}]
```

So the second validation is only applied if a common set isn't included in the validate invocation.

**Comment by leonardoborges** [comment]
Hi @OliverM ,

Just got back from holidays so apologies for the delay on this.

The behaviour you describe is as designed. From the docstring of `validate`:

```clojure
"Takes a

  - `message-fn` (optional) responsible for transforming error metadata into
  the validation result (defaults to `with-default-messages`)

  - `m` map to be validated

  - `forms` validations to be performed on the map

  forms can be a single validator set or a sequence of key/value pairs where:

 ..."
```

Specifically, it says that *forms can be a single validator set* **or** *a sequence of key/value pairs...*. That is, if using a validator set, all validations should be part of the set. Your example can then be rewritten as:

```clojure
(b/validate {:field1 "Present" :field2 2} 
                 (assoc common-validations 
                             :field2 [[bv/boolean :message "Field 2 not a boolean"]]))
;; [{:field2 ("Field 2 not a boolean")} {:bouncer.core/errors {:field2 ("Field 2 not a boolean")}, :field2 2, :field1 "Present"}]

```

I'm sorry this tricked you. I'll add an item to the backlog to validate the input and let the user know she should be using only one or the other.
