### ISSUE TITLE
Personal error for every item in vector

### ISSUE THREAD

**Issue by BooBSD** [leonardoborges/bouncer#50]
Hello,

Is it possible to get personal error for every item in vector? Something like this:

```
[{:contact {:phones [nil "Incorrect phone" nil]}}
 {:contact {:phones ["123-4567" :wrong "456-7890"]},
  :bouncer.core/errors {:contact {:phones [nil "Incorrect phone" nil]}}}]
```
Thank you!

**Comment by leonardoborges** [comment]
I believe this is also being discussed in #43 - Mind checking its content and adding to the ticket?
